# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodingItWrong.com
author: Josh Justice
email: me@codingitwrong.com
description: > # this means to ignore newlines until "baseurl:"
  Passionate about making development easier by removing accidental complexity and promoting evolutionary design, good abstractions, and end-user programming. Web Platform Lead at Big Nerd Ranch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codingitwrong.com" # the base hostname & protocol for your site
github_username:  CodingItWrong
mastodon:
  -
    username: CodingItWrong
    instance: mastodon.technology
google_analytics: 'G-B9G24QHNZH'

# Build settings
markdown: kramdown
theme: jekyll-theme-codingitwrong
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Josh Justice

kramdown:
  input: GFM
